apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultimate-cicd-deployment
spec:
  replicas: 5  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ultimate-cicd
  template:
    metadata:
      labels:
        app: ultimate-cicd
    spec:
      containers:
      - name: ultimate-cicd-container
        image: lubern5/netflix:latest
        ports:
        - containerPort: 80
